#修改端口号server:
server:
  port: 8080
#加载驱动
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&amp;characterEncoding=UTF8&amp;useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#显示sql语句
  jpa:
    show-sql: true
    #mysql数据库方言
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#自动更新(最好用update)
        ddl-auto: update

cupSize: f
name: 王梦丽
age: 24

girl:
  name: 娜美
  age: 18
  cupSize: G