spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true


cupSize: f
name: 王梦丽
age: 24

girl:
  name: 林志玲
  age: 55
  cupSize: H
